# Generated by Django 2.0.7 on 2018-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='storeregion',
            field=models.CharField(default='charField', max_length=200),
        ),
    ]
