# Generated by Django 2.0.7 on 2018-09-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_password'),
        ('store', '0003_store_storeregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='userid',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
