# Generated by Django 2.0.7 on 2018-09-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storereview_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='storepoint',
            field=models.CharField(default='5', max_length=200),
        ),
    ]
