# Generated by Django 2.0.7 on 2018-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180910_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereview',
            name='storepoint',
            field=models.IntegerField(default='5'),
        ),
    ]
