# Generated by Django 2.0.7 on 2018-10-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_storeshutdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='storelatitude',
            field=models.CharField(default='176.4', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='storelongitude',
            field=models.CharField(default='-145.3', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='storepoint',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='storereview',
            name='storepoint',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
