# Generated by Django 2.0.7 on 2018-10-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20181013_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereview',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
