# Generated by Django 2.0.7 on 2018-08-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180808_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accesstoken',
            field=models.CharField(default='charField', max_length=200),
        ),
    ]
