# Generated by Django 2.0.7 on 2018-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_accesstoken_itself'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
