# Generated by Django 2.0.7 on 2018-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='charField', max_length=200),
        ),
    ]
