# Generated by Django 2.0.7 on 2018-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(default='charField', max_length=200),
        ),
    ]
